global:
  resolve_timeout: 5m
route:
  receiver: webhook_receiver
  group_by: [alertname]
#  repeat_interval: 5m
receivers:
    - name: webhook_receiver
      webhook_configs:
        - url: 'http://discord:9094'
          send_resolved: true

