version: "2"

networks:
  grafana:
    external: false

services:
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - grafana
    restart: always

  grafana:
    image: grafana/grafana-oss
    ports:
      - "3000:3000"
    networks:
      - grafana
    restart: always

  node-exporter:
    image: ubuntu
    networks:
      - grafana
    volumes:
      - ./node-exporter/entrypoint.sh:/opt/entrypoint.sh
    entrypoint: ["/opt/entrypoint.sh"]
