version: "2"

networks:
  grafana:
    external: false

services:
  server:
    image: nginx
    volumes:
      - ./exporter/metrics:/usr/share/nginx/html/metrics
      - ./exporter/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "9000:9000"
    networks:
      - grafana
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus:/etc/prometheus
    ports:
      - "9090:9090"
    networks:
      - grafana
    restart: always

  discord:
    image: benjojo/alertmanager-discord
    environment:
        - DISCORD_WEBHOOK=https://discord.com/api/webhooks/1054592709299552397/qcBPxfUpmbFiLTkKTQuxa_XPVdfzJFMyuX_MHDxN64hfEq5rfQ20Pbw_rLh2yzd53m7P
    networks:
      - grafana
    restart: always

  alertmanager:
    image: prom/alertmanager
    volumes:
      - ./alertmanager:/etc/alertmanager
    ports:
      - "9093:9093"
    networks:
      - grafana
    restart: always

  grafana:
    image: grafana/grafana-oss
    volumes:
      - ./grafana/datasources/prometheus.yml:/etc/grafana/provisioning/datasources/prometheus.yml
      - ./grafana/dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    ports:
      - "3000:3000"
    networks:
      - grafana
    restart: always
