version: "2.1"

networks:
  grafana:
    external: false

services:
  fakeserver:
    image: nginx
    volumes:
      - ./fakeserver/metrics:/usr/share/nginx/html/metrics
      - ./fakeserver/data:/usr/share/nginx/html/data
      - ./fakeserver/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8081:8080"
    networks:
      - grafana
  frmcompanion:
    image: golang
    working_dir: /usr/src
    entrypoint: /usr/local/bin/init.sh
    volumes:
      - ./frmcompanion/init.sh:/usr/local/bin/init.sh
    environment:
      - FRM_HOST=${FRM_HOST:-fakeserver}
      - FRM_PORT=${FRM_PORT:-8080}
    ports:
      - "9000:9000"
      - "8000:8000"
    networks:
      - grafana
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus:/etc/prometheus
    ports:
      - "9090:9090"
    networks:
      - grafana
    restart: always

  discord:
    image: benjojo/alertmanager-discord
    environment:
        - DISCORD_WEBHOOK=${DISCORD_WEBHOOK}
    networks:
      - grafana
    restart: always

  alertmanager:
    image: prom/alertmanager
    volumes:
      - ./alertmanager:/etc/alertmanager
    ports:
      - "9093:9093"
    networks:
      - grafana
    restart: always

  grafana:
    image: grafana/grafana-oss
    volumes:
      - ./grafana/datasources/prometheus.yml:/etc/grafana/provisioning/datasources/prometheus.yml
      - ./grafana/dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
    ports:
      - "3000:3000"
    networks:
      - grafana
    restart: always
