global:
  scrape_interval: 15s
  evaluation_interval: 10s
rule_files:
  - rules/*.yml

alerting:
  alertmanagers:
  - static_configs:
    - targets:
       - alertmanager:9093

scrape_configs:
  - job_name: node
    file_sd_configs:
      - files:
        - nodes/*.yml
    metric_relabel_configs:
      - regex: "^(job|instance)$"
        action: labeldrop

