groups:
  - name: Power
    rules:
    - alert: FuseTriggered
      expr: fuse_triggered > 0
      labels:
        category: power
      annotations:
        summary: "Fuse triggered on circuit {{ $labels.circuit_id }}"
        description: Fuse triggered - a power grid is without power.
    - alert: BatteryDrained
      expr: 0 < battery_seconds_empty and battery_seconds_empty < 1800
      for: 10s
      labels:
        category: power
      annotations:
        summary: "Under 30 minutes of power left on circuit {{ $labels.circuit_id }}"
        description: A battery has nearly drained on circuit {{ $labels.circuit_id }}. Under thirty minutes of power remaining.
    - alert: BatteryDraining
      expr: battery_differential < 0
      for: 10s
      labels:
        category: power
      annotations:
        summary: "Battery draining on circuit {{ $labels.circuit_id }}"
        description: A battery has started to drain on circuit {{ $labels.circuit_id }}.
    - alert: MaxConsumption
      expr: power_capacity < power_max_consumed
      for: 10s
      labels:
        category: power
      annotations:
        summary: "Max consumption too high on circuit {{ $labels.circuit_id }}"
        description: Max consumption on power grid {{ $labels.circuit_id }} has exceeded production. Power instability may occur.
